### ISSUE TITLE
Markers published by visualize_sensors generate TF errors in RViz

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/takktile_ros#3]
I followed the instructions in the README to start the visualization:

``` shell
$ rosrun takktile_ros visualize_sensors.py layout_descriptions/barrett_hand.yml
$ roslaunch urdf_tutorial display.launch model:=/home/mkoval/herb-ws/devel/share/herb_description/robots/bh280.urdf
```

This works, but the `Markers` topic in RViz constantly flickers red with a warning about being "unable to transform to fixed frame". Maybe there are more timestamp issues on the markers that we're publishing?

**Comment by ClintLiddick** [comment]
resolved by personalrobotics/takktile_ros@ce6e6149093c2f218d5e105fe9a755ac2b029223
