### ISSUE TITLE
TakkTile-usb is not a valid name for a Catkin package

### ISSUE THREAD

**Issue by mkoval** [personalrobotics/takktile_ros#4]
Catkin packages must have lowercase, alpha-numeric names. The only special symbol allowed is the underscore. `TakkTile-usb` is not a valid Catkin package name and causes `rosdep` to complain when it's checked out in a workspace.

**Comment by ClintLiddick** [comment]
fixed by personalrobotics/TakkTile-usb@b1421f9d7410cbf0f149b244d3344dc93bae3d64
